interface CategoriesType {
  [key: string]: string[];
}

const categories: CategoriesType = {
  Personendaten: [
    "NameFirma",
    "Vorname",
    "Straße",
    "Hausnr",
    "Rufnummern Mitnahme",
    "PLZ",
    "Ort",
    "Anbieterwechselauftrag von",
    "Kndigen von",
    "Alten Vertrag Kuendigen",
  ],
  Rufnummern: [
    "Rufnummern Mitnahme alle Nr der Anschluesse portieren",
    "Rufnummern Mitnahme Ortskennzahl",
    "Rufnummern Mitnahme Ortskennzahl 2",
    "Rufnummern Mitnahme Rufnummer 1",
    "Rufnummern Mitnahme Rufnummer 2",
    "Rufnummern Mitnahme Rufnummer 3",
    "Rufnummern Mitnahme Rufnummer 4",
    "Rufnummern Mitnahme Rufnummer 5",
    "Rufnummern Mitnahme Rufnummer 6",
    "Rufnummern Mitnahme Rufnummer 7",
    "Rufnummern Mitnahme Rufnummer 8",
    "Rufnummern Mitnahme Rufnummer 9",
    "Telekommonikations Anlagen Duchwahl-RN",
    "Telekommonikations Anlagen Abfragestelle",
    "Telekommonikations Anlagen Ruffnummernblock von",
    "Telekommonikations Anlagen Ruffnummernblock bis",
    "Ort Datum",
    "Vertragspartner und ggf Firmenstempel",
  ],
  Endkundenvertragspartner: [
    "WBCIGF",
    "Vorab-ID",
    "Änderungs-Storno-ID",
    "PKlauf",
    "Wechseltermin",
    "Neuer Wechseltermin",
    "Portierungsfenster 6 - 8 Uhr",
    "Portierungsfenster 6 - 12 Uhr",
    "Portierungsfenster Wunschuhrzeit",
    "Portierungsfenster Wunschuhrzeit eingeben",
    "Rückinformation an",
    "über FaxEMail",
    "Tel",
    "Ressourcenübernahme ja",
    "Ressourcenübernahme nein",
    "Sicherer Hafen",
    "Storno ausgeführt ja",
    "Storno ausgeführt nein",
    "ZWA",
    "NAT",
    "ADA",
    "Zustimmungsdatum",
    "IstTechnologie",
    "WITA",
    "SPRI",
    "WITAVertragsnummer LineID",
    "Grund",
    "ADF",
    "KNI",
    "VAE",
    "RNG",
    "WAI",
    "AIF",
    "SON",
    "Ortsnetzkennzahl",
    "Rufnummer/n [1]",
    "Rufnummer/n [2]",
    "Rufnummer/n [3]",
    "Rufnummern 4",
    "Rufnummern 5",
    "PKIabg [1]",
    "PKIabg [2]",
    "PKIabg [3]",
    "PKIabg [4]",
    "PKIabg [5]",
    "Rufnummer/n [6]",
    "Rufnummer/n [7]",
    "Rufnummer/n [8]",
    "Rufnummer/n [9]",
    "Rufnummer/n [10]",
    "PKIabg [6]",
    "PKIabg [7]",
    "PKIabg [8]",
    "PKIabg [9]",
    "PKIabg [10]",
    "Bei Telekommunikationsanlagen Duchwahl-RN",
    "Bei Telekommunikationsanlagen Abfragestelle",
    "Bei Telekommunikationsanlagen Rufnummernblock von",
    "Bei Telekommunikationsanlagen Rufnummernblock bis",
    "Bei Telekommunikationsanlagen PKI abg",
    "Bei Telekommunikationsanlagen MSNf",
    "Ansprechpartner",
    "über FaxEMail_2",
    "Tel_2",
    "interne Bemerkungen",
  ],
};

export { categories };
